[[pages]]
path = "/"
screenshotTimestamp = "2026-04-23T19:39:18Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8776c0ce-96aa-40df-8ecf-c8e02a98fecb/675e6bcb-f8aa-4727-8aea-eb195964e8f0/hVTssRB"
